
# Set the stack name
name: lf_dev
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lf_dev_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ingest/:/ingest/

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    # on arm macos we have two options: emulate the platform (slow) or use another image.
    # unfortunately, `mcr.microsoft.com/azure-sql-edge:latest` has no support for
    # common language runtime (CLR) which we need for date formatting.
    # Note: to get emulation working proper, you need to enable rosetta
    # in docker desktop settings: https://stackoverflow.com/a/75975040/22346289
    container_name: lf_dev_mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BetterUseP0stgres!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'BetterUseP0stgres!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssqldata:/var/opt/mssql
      - ./ingest/:/ingest/

volumes:
  pgdata:
  mssqldata:
